// =============================================================================
// ESLint flat config -- Next.js + security
// =============================================================================
// Generated by /make-it scaffold (nextjs-fullstack)
// =============================================================================

import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";
import security from "eslint-plugin-security";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

export default [
  ...compat.extends("next/core-web-vitals", "next/typescript", "prettier"),
  security.configs.recommended,
  {
    rules: {
      "no-eval": "error",
      "no-implied-eval": "error",
    },
  },
  {
    ignores: [".next/", "node_modules/", "coverage/"],
  },
];
