#!/usr/bin/env bash
# =============================================================================
# Worktree helper -- isolated parallel checkouts for [APP_NAME]
# =============================================================================
# Generated by /make-it scaffold. Stack-agnostic (reads ports from compose).
#
# A git worktree is a second working directory for another branch, linked to the
# same repo. Use one per concurrent task so you never stash/commit unfinished
# work to switch context, and parallel sessions never clobber each other.
#
# This helper also makes "docker compose up" collision-free across worktrees by
# seeding each new worktree's .env with a unique COMPOSE_PROJECT_NAME and host
# ports offset by a deterministic amount derived from the branch name.
#
# Usage:
#   scripts/worktree.sh new <branch> [base-ref]   # create + seed an isolated worktree
#   scripts/worktree.sh list                       # list worktrees
#   scripts/worktree.sh rm  <branch> [--force]     # remove a worktree and prune
# =============================================================================
set -euo pipefail

die() { printf 'worktree: %s\n' "$1" >&2; exit 1; }

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || die "not inside a git repository"
SLUG="$(basename "$ROOT")"
WT_PARENT="$(dirname "$ROOT")/${SLUG}-worktrees"

# Deterministic port offset (100..8000, step 100) from a branch name.
offset_for() {
  local sum
  sum="$(printf '%s' "$1" | cksum | awk '{print $1}')"
  echo "$(( (sum % 80 + 1) * 100 ))"
}

# Upsert KEY=VALUE in an env file.
set_env() {
  local f="$1" k="$2" v="$3"
  touch "$f"
  grep -v "^${k}=" "$f" > "${f}.tmp" 2>/dev/null || true
  mv "${f}.tmp" "$f"
  printf '%s=%s\n' "$k" "$v" >> "$f"
}

wt_path() {
  printf '%s/%s' "$WT_PARENT" "$(printf '%s' "$1" | tr '/ ' '__')"
}

cmd_new() {
  local branch="${1:-}" base="${2:-HEAD}"
  [ -n "$branch" ] || die "usage: worktree.sh new <branch> [base-ref]"
  local wt; wt="$(wt_path "$branch")"
  [ -e "$wt" ] && die "worktree path already exists: $wt"
  mkdir -p "$WT_PARENT"

  if git show-ref --verify --quiet "refs/heads/$branch"; then
    git worktree add "$wt" "$branch"
  else
    git worktree add -b "$branch" "$wt" "$base"
  fi

  # Seed an isolated env file.
  if [ -f "$ROOT/.env" ]; then cp "$ROOT/.env" "$wt/.env"
  elif [ -f "$ROOT/.env.example" ]; then cp "$ROOT/.env.example" "$wt/.env"
  fi

  local offset; offset="$(offset_for "$branch")"
  local proj="${SLUG}-$(printf '%s' "$branch" | tr '/ ' '__')"
  set_env "$wt/.env" COMPOSE_PROJECT_NAME "$proj"

  # Offset every host port that compose exposes via ${VAR:-default}.
  local compose="$ROOT/docker-compose.yml"
  if [ -f "$compose" ]; then
    grep -oE '\$\{[A-Z0-9_]+:-[0-9]+\}' "$compose" \
      | sed -E 's/\$\{([A-Z0-9_]+):-([0-9]+)\}/\1 \2/' \
      | sort -u \
      | while read -r var def; do
          set_env "$wt/.env" "$var" "$(( def + offset ))"
        done
  fi

  printf '\nCreated worktree:\n  branch : %s\n  path   : %s\n  project: %s (port offset +%s)\n\nNext:\n  cd %s\n  docker compose --profile dev up --build\n' \
    "$branch" "$wt" "$proj" "$offset" "$wt"
}

cmd_rm() {
  local branch="${1:-}"; shift || true
  [ -n "$branch" ] || die "usage: worktree.sh rm <branch> [--force]"
  local wt; wt="$(wt_path "$branch")"
  git worktree remove "$wt" "$@" || die "remove failed (try: worktree.sh rm $branch --force)"
  git worktree prune
  printf 'Removed worktree: %s\n' "$wt"
}

case "${1:-}" in
  new)  shift; cmd_new "$@" ;;
  list) git worktree list ;;
  rm|remove) shift; cmd_rm "$@" ;;
  *) sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//' ;;
esac
